// Tracks and their chapters.
// A chapter with a `load` function has lessons and challenges in this app.
// To add a chapter: write its content file, add a `load` line here,
// and add the file to CORE in sw.js.

export const tracks = [
  {
    id: 'cpp',
    title: 'C++',
    unit: 'Chapter',
    blurb: 'The language itself. Nothing is locked, so skip ahead whenever a topic is review.',
    // Order and titles follow the table of contents at learncpp.com.
    chapters: [
      { num: '0', title: 'Introduction and getting started' },
      { num: '1', title: 'C++ basics', load: () => import('./ch01.js') },
      { num: '2', title: 'Functions and files', load: () => import('./ch02.js') },
      { num: '3', title: 'Debugging C++ programs' },
      { num: '4', title: 'Fundamental data types' },
      { num: '5', title: 'Constants and strings' },
      { num: '6', title: 'Operators' },
      { num: 'O', title: 'Bit manipulation (optional)' },
      { num: '7', title: 'Scope, duration, and linkage' },
      { num: '8', title: 'Control flow' },
      { num: '9', title: 'Error detection and handling' },
      { num: '10', title: 'Type conversion, type aliases, and type deduction' },
      { num: '11', title: 'Function overloading and function templates' },
      { num: 'F', title: 'Constexpr functions' },
      { num: '12', title: 'Compound types: references and pointers' },
      { num: '13', title: 'Compound types: enums and structs' },
      { num: '14', title: 'Introduction to classes' },
      { num: '15', title: 'More on classes' },
      { num: '16', title: 'Dynamic arrays: std::vector' },
      { num: '17', title: 'Fixed-size arrays: std::array and C-style arrays' },
      { num: '18', title: 'Iterators and algorithms' },
      { num: '19', title: 'Dynamic allocation' },
      { num: '20', title: 'Functions' },
      { num: '21', title: 'Operator overloading' },
      { num: '22', title: 'Move semantics and smart pointers' },
      { num: '23', title: 'Object relationships' },
      { num: '24', title: 'Inheritance' },
      { num: '25', title: 'Virtual functions' },
      { num: '26', title: 'Templates and classes' },
      { num: '27', title: 'Exceptions' },
      { num: '28', title: 'Input and output (I/O)' },
    ],
  },
  {
    id: 'emb',
    title: 'Embedded',
    unit: 'Unit',
    blurb: 'What is specific to firmware: how code reaches a device, where it lives in memory, and how it talks to hardware. Unit M1 is the bigger picture and needs only C++ chapters 1 and 2.',
    chapters: [
      { num: 'M1', title: 'From source code to a running device', load: () => import('./m1.js') },
      { num: 'M2', title: 'Memory: stack, heap, and static' },
      { num: 'M3', title: 'Bits, registers, and fixed-width types' },
      { num: 'M4', title: 'const, volatile, and talking to hardware' },
      { num: 'M5', title: 'Interrupts and shared data' },
      { num: 'M6', title: 'State machines and the main loop' },
      { num: 'M7', title: 'Buffers and serial communication' },
      { num: 'M8', title: 'RTOS basics: tasks, queues, and timing' },
      { num: 'M9', title: 'Debugging on real hardware' },
      { num: 'M10', title: 'Embedded interview questions' },
    ],
  },
  {
    id: 'eng',
    title: 'Engineering',
    unit: 'Unit',
    blurb: 'The habits that make an engineer reliable, and that interviews test: debugging, testing, design, data structures and how software gets built. Unit E1 needs only C++ chapter 1.',
    // The habits and bigger-picture knowledge that make an engineer reliable,
    // and that interviews test. Units use C++ as the working language.
    chapters: [
      { num: 'E1', title: 'Finding and fixing bugs', load: () => import('./e1.js') },
      { num: 'E2', title: 'Writing code other people can read' },
      { num: 'E3', title: 'Breaking a problem down' },
      { num: 'E4', title: 'Testing' },
      { num: 'E5', title: 'Data structures' },
      { num: 'E6', title: 'How fast is it? Complexity' },
      { num: 'E7', title: 'Version control and code review' },
      { num: 'E8', title: 'How software gets built and shipped' },
      { num: 'E9', title: 'Interview problem solving' },
    ],
  },
];
